### ISSUE TITLE
quilt 1.20 ubes delight 0.1.4 cant fing ginger anywhere

### ISSUE THREAD

**Issue by thecloudking** [ChefMooon/ubes-delight#12]
i have terralith installed as my only biome-adding/altering mod. i found ube, sweet potato, and garlic just fine both in the 'nilla jungle biomes as well as in the terralith jungle-type biomes, but i can't find ginger anywhere

**Comment by thecloudking** [comment]
![explorer_uwvv3SHZ1f](https://github.com/ChefMooon/ubes-delight/assets/96870182/fd076e70-bd13-49c9-b137-b51c7bfe0d7f)

i did make a new world and after some searching i found ginger in a vanilla sparse jungle, but the original world i couldn't find ginger in had very large regular jungle biomes and only occasional small sparse jungle. a second world i generated to test further also had ginger in regular jungle. i have made very few changes to my mod folder since generating the bugged world in question, and the only ones i removed have been bodacious berries and beetlebox. and even then i've looked for ginger after removing bodacious berries for adding just too many grape vines to jungles and havent found any, and i cant think of why beetlebox would effect it either

**Comment by neverdestroyer23** [comment]
im pretty sure this counts as fixed

**Comment by ChefMooon** [comment]
V0.2.0 should fix this. Fabric will use the c:jungle tag that is also used in terralith and other World Gen mods. Also, thanks for the extra info!

- World Generation Improvements
   - Wild Ube, Garlic, Ginger, Lemongrass biome spawning can now be configured
   - Fabric
      - Uses c:jungle should improve compatibility with World Gen mods
      - Biomes can now be added to a Whitelist/Blacklist
      - data/ubesdelight/tags/worldgen/biome/has_wild_ube_whitelist.json
      - data/ubesdelight/tags/worldgen/biome/has_wild_ube_blacklist.json
   - Forge
      - Uses minecraft:jungle, minecraft:bamboo_jungle, minecraft:sparse_jungle
      - Biomes can be added to allowed_boimes/denied_biomes
      - data/ubesdelight/forge/biome_modifier/wild_ube.json
