### ISSUE TITLE
[1.20.1] Halo Halo consumes the glass bottle

### ISSUE THREAD

**Issue by PoneyClairDeLune** [ChefMooon/ubes-delight#15]
**Describe the bug**
When drinking Halo Halo, the glass bottle/cup gets consumed as well

**To Reproduce**
1. Obtain a cup of Halo Halo
2. Drink the cup

**Expected behavior**
The cup/bottle gets consumed.

**Screenshots or Videos**
N/A

**Crash Report or Log**
N/A

**Operating System**

**Mod Version**

**Minecraft Version**

**Fabric/Forge Version**

**Other Mods**
Please provide a list of all mods also being used.

**Additional context**

**Comment by ChefMooon** [comment]
Really appreciate you opening this issue, apologies to all those who lost bottles. This will be fixed in the next update (V0.1.5.3). I will close this issue once it is released. Thank you for checking out the mod!

**Comment by ChefMooon** [comment]
Update Released. V0.1.5.3([Modrinth](https://modrinth.com/mod/ubes-delight/version/J35QW9iW)-[CF](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files/5236861))
