### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [ChefMooon/ubes-delight#16]
**Describe the Suggestion**

An update for the new fabric port of Farmer's Delight.

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated

**Additional context**

The new port has less ambiguous code, is less buggy and is faithful to the original forge mods codebase. It would be much appreciated if compat was added for this port.

**Comment by ChefMooon** [comment]
Appreciate you opening the enhancement and checking out Ube's Delight! V0.1.5.3([Modrinth](https://modrinth.com/mod/ubes-delight/version/J35QW9iW)-[CF](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files/5236861)) adds compatibility with Farmer's Delight Refabricated 2.0.10+.
