### ISSUE TITLE
[Compat] JEI Integration

### ISSUE THREAD

**Issue by bin200** [ChefMooon/ubes-delight#19]
I'd like to suggest integration with the Just Enough Items mod for the Baking Mat recipe type. The REI integration is good but I prefer to use EMI, which can pull its recipes from JEI so there's usually not any problems. Integration with both REI and JEI would help this mod fit smoothly into more modpacks! Thanks for the consideration.

**Comment by ChefMooon** [comment]
Appreciate the suggestion! Fortunately, the next version adds JEI and EMI support, helping make Baking Mat recipes more viewable in-game. The beta version is available in the [Discord](https://discord.gg/mbuDBHHUws), with a full release coming soon!
