### ISSUE TITLE
[SUGGESTION] Compat with Snowy Spirit

### ISSUE THREAD

**Issue by Sunconure11** [ChefMooon/ubes-delight#2]
Even though these two mods might as well be night and day, both have Farmers Delight support, and both add ginger.

**Comment by Sunconure11** [comment]
Furthermore, several mods add garlic.

I suggest config options to turn off gen for your garlic and ginger.

**Comment by ChefMooon** [comment]
Hello @Sunconure11,

I appreciate your suggestion! For version 0.1.2 I went through each food recipe and ensured they use the common c:crop tags and added Ube's Delight crops to the the c tag. Hopefully this will cover compatibility however I am developing and testing in Minecraft 1.20.1 so I have not had a chance to test compatibility with mods other than Farmer's Delight. 

Also, adding Mod Menu integration it should ensure easier access to configuration. 

If you find more compatibility issues I will look into them as well.

**Comment by Sunconure11** [comment]
Bewitchment and Assorted Discoveries both have garlic.

**Comment by Sunconure11** [comment]
I'd suggest bringing these changes to 1.19.2 as well,

**Comment by Sunconure11** [comment]
As for a new crop entirely... maybe red beans? I've seen some recipes for halo-halo that use it.

**Comment by Sunconure11** [comment]
Another improvement would be Fabric Seasons compat, since a lot of these plants are tropical, with the exception of garlic

**Comment by Sunconure11** [comment]
@ChefMooon Garlic cloves need a different tag. With mods like Almost Unified, they cease existing.

**Comment by Sunconure11** [comment]
![image](https://github.com/ChefMooon/ubes-delight/assets/5614902/9502c5e6-80af-4357-ae56-787b9dde3f57)

**Comment by Sunconure11** [comment]
Also, of note, is that Snowy Spirit adds both ginger flowers (which are used to grow more), and ginger roots.

**Comment by ChefMooon** [comment]
Apologies for the long wait on the response, but all of the integration suggestions as well as the garlic bugs should be addressed as of version V0.1.4.

Fabric Seasons compatibility: 3 crops complete, Lemongrass in the works.
2 new configuration options to enable/disable extra chopping recipes.
New recipes to chop vegetables from these mods if they are loaded;
- Garlic
   - Bewitchment
   - Assorted Discoveries
- Ginger
   - SnowySpirit

Also appreciate the kidney bean suggestion, I will keep it in mind! There are plans for a new ingredient, but will be trying to keep the base ingredients small for this pack.
