### ISSUE TITLE
[1.20.1] Can't Harvest Crops

### ISSUE THREAD

**Issue by SleepiiRaven** [ChefMooon/ubes-delight#22]
When harvesting any of the crops (even after fully grown with bone meal), I can break them but they don't drop anything!

1. Place farmland next to water
2. Place garlic, ginger, lemongrass, or ube on the farmland
3. Bone meal
4. Harvest 

It's supposed to drop the crop, right?

Windows 11

fabric-0.2.0-beta-1

Fabric 0.15.11

**Comment by ChefMooon** [comment]
Thank you for opening the bug! They are indeed supposed to drop the crop, looks like the loot table generator doesn't want to generate those anymore. I'll add them in manually and release a 0.2.0-beta-2 shortly to fix them. Apologies for the bug, appreciate your time!

**Comment by ChefMooon** [comment]
V0.2.0-beta-2 has been released. Thanks again!

Fabric Versions - [Modrinth](https://modrinth.com/mod/ubes-delight/version/fabric-0.2.0-beta-2) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files/5656952).
