### ISSUE TITLE
incompatible with 1.21.1 

### ISSUE THREAD

**Issue by VaporeonScripts** [ChefMooon/ubes-delight#25]
**Describe the bug**
When i put latest version of this fabric mod, it will say its incompatible with 1.21.1

**To Reproduce**
put it, start the game

**Expected behavior**
![image](https://github.com/user-attachments/assets/a4441258-ca34-4bfb-9621-8f3c3aa18353)

**Screenshots or Videos**
![image](https://github.com/user-attachments/assets/027af639-2ba4-4ac6-883f-812c1baa455b)

**Crash Report or Log**
no

**Operating System**
CachyOS (arch linux distro)
**Mod Version**
latest
**Minecraft Version**
1.21.1
**Fabric/Forge Version**
fabric
**Other Mods**
Please provide a list of all mods also being used.
no need,as its the mod itself not being coompatible with 1.21.1
**Additional context**
no

**Comment by ChefMooon** [comment]
Thank you so much for opening the bug! I'll be releasing a new version shortly with a fix for this bug.

**Comment by ChefMooon** [comment]
1.21-0.2.0-beta-2 has been released! Found a couple more fixes as well. Appreciate your time!

:link: [Modrinth](https://modrinth.com/mod/ubes-delight/version/fabric-1.21-0.2.0-beta-2) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files/5697453) :link:

**Comment by VaporeonScripts** [comment]
no problem, ty for developing this fantastic mod!
