### ISSUE TITLE
[Minecraft Version(eg.1.21.1)] Stuck in the Loading Screen 

### ISSUE THREAD

**Issue by TipsyNeko** [ChefMooon/ubes-delight#26]
**Describe the bug**
Stuck at the loading screen with no crash report, so no incompatible report at all  

**To Reproduce**
Adding the mod to the mod folder and start the game 

**Expected behavior**
Stuck at the loading screen and no more progression when loading 

**Screenshots or Videos**
<img width="852" alt="Failed Screenshot " src="https://github.com/user-attachments/assets/eb63cd30-68b0-4201-8dbb-98997f9147c4">

https://github.com/user-attachments/assets/39c82aad-bebb-4778-9d7f-08795acf8734

**Crash Report or Log**
No crash Report as no crash happen

**Operating System**
MAC OS System

**Mod Version**
1.12.1- 0.2.0-beta-2

**Minecraft Version**
1.21.1

**Fabric/Forge Version**
Fabric

**Other Mods**
<img width="772" alt="Mod List 1" src="https://github.com/user-attachments/assets/1fb2e6d0-5697-4016-9157-61e5c7424381">
<img width="772" alt="Mod List 2" src="https://github.com/user-attachments/assets/67b45c31-faf2-46f9-97c4-24f4337325f6">
<img width="772" alt="Mod List 3" src="https://github.com/user-attachments/assets/2c810146-8b42-46ea-8f45-5a3b6e814ede">
<img width="772" alt="Mod List 4" src="https://github.com/user-attachments/assets/716ea3f2-3a22-4a80-aa5a-d3b487ee89b9">
<img width="772" alt="Mod List 5" src="https://github.com/user-attachments/assets/22b671a0-4230-4700-822b-a9f48017ee4e">
<img width="772" alt="Mod List 6" src="https://github.com/user-attachments/assets/296c61e1-50d1-4ebf-89d4-8039eeaf2a1f">
<img width="772" alt="Mod List 7" src="https://github.com/user-attachments/assets/7a4def73-b489-46ab-a6f6-533d94e42ba2">

**Comment by ChefMooon** [comment]
Appreciate you opening the bug report and checking out the mod! I have tried a few quick tests with some of the mods but have not been able to replicate the bug, just wanted to update here. I will attempt to try with the full modlist when I have more time. If anyone had a log file (logs/latest.txt), that might help identify the issue faster. I will update when I can test more! Really appreciate all the information you provided!

**Comment by TipsyNeko** [comment]
was going to try again to recreate the bug but the game is able to load now, couldn't post the log because doesnt know how to show log file
