### ISSUE TITLE
[1.21.1 NeoForge 21.0.167] broken kalan recipe

### ISSUE THREAD

**Issue by bunpril** [ChefMooon/ubes-delight#27]
**Describe the bug**
unable to make the kalan, in my JEI menu the recipe shows "Empty Tag:  c:iron_ingots" with the error icon

**To Reproduce**
placing the recipe with 7 terracotta, 1 campfire, and 1 iron ingot does not create the kalan

**Expected behavior**

**Screenshots or Videos**
![ubesdelightbug](https://github.com/user-attachments/assets/83b9a239-fcfc-4315-99b0-f7a36549928f)

**Operating System**
win 11
**Mod Version**
0.2.0
**Minecraft Version**
1.21.1
**Fabric/Forge Version**
neoforge 21.0.167
**Other Mods**
farmer's delight
JEI 
pufferfish's skills + attributes
farmer's structures
easy anvils
easy magic
mrcrayfish's furniture mod: refurbished
xareo's minimap
clumps
tree harvester
Please provide a list of all mods also being used.

**Additional context**

**Comment by ChefMooon** [comment]
Appreciate you opening the issue! I’ve fixed the issue in development, and it will be included in version 0.2.0-beta-3, though it still needs a bit more work before release. If you would like to fix it right away I have attached a datapack that fixes the recipe. (Idea from discord, thank you!) If you add it to the datapack folder of your world you will be able to craft the kalan.

[udKalanRecipeFix.zip](https://github.com/user-attachments/files/17118581/udKalanRecipeFix.zip)

**Comment by bunpril** [comment]
waahhhh thank u sm :) 🖤 having so much fun with the ube recipes !!

**Comment by ChefMooon** [comment]
Just released version 0.2.0, which includes this fix. Glad you are enjoying the mod! New features are currently in development!

[Modrinth](https://modrinth.com/mod/ubes-delight/version/neoforge-1.21-0.2.0) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files/5777579)
