### ISSUE TITLE
update embedded midnight lib?

### ISSUE THREAD

**Issue by VaporeonScripts** [ChefMooon/ubes-delight#28]
**Describe the Suggestion**
update embedded midnight lib

**Screenshots and Videos**
![image](https://github.com/user-attachments/assets/361ebaf5-2d69-4d33-aa27-47ad341c2945)
![image](https://github.com/user-attachments/assets/51c1485c-ab46-4c89-b90d-d5984d06050c)

**Additional context**
nothing much
(1.21.1 neoforge .66)

**Comment by ChefMooon** [comment]
Thank you for letting me know, apologies it took a while. Updated to v1.6.4 in Ube's Delight v0.2.1. ([Modrinth](https://modrinth.com/mod/ubes-delight/versions) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/ubes-delight/files))
