### ISSUE TITLE
1.19.2 quilt garlic won't chop (update 0.1.3-p1-1.19.2)

### ISSUE THREAD

**Issue by reefridgeerator** [ChefMooon/ubes-delight#5]
Chopped garlic is unobtainable; the chopped garlic recipe shows up with a blank on the cutting board in REI. Additionally chopped garlic shows up as garlic cloves in REI.

![image](https://github.com/ChefMooon/ubes-delight/assets/73477021/07bc7fb5-a1a4-4400-b39f-77a1f5d70abb)
(ignore the particles its just some milk)

**Comment by ChefMooon** [comment]
Appreciate you reporting this! Looks like I missed a garlic tag while porting from 1.20 to 1.19.2. Apologies to the 1.19.2 players for the broken garlic.

This will be fixed in the next update. Should be out within the day, I will close this once the commit has been made.

**Comment by sh0tybumbati** [comment]
There's actually a hilarious unintended side effect of this-
garlic crates are craftable with 9 'air' blocks, so by default, any of my blank crafting tables can create a crate of garlic for free automatically lol

**Comment by ChefMooon** [comment]
> There's actually a hilarious unexpected side effect of this- garlic crates are craftable with 9 'air' blocks, so by default, any of my blank crafting tables can create a crate of garlic for free automatically ![image](https://user-images.githubusercontent.com/39677663/262752823-88a52f59-ce1c-42b8-877f-ca6418f9c923.png)

Oh my, haha magic garlic crates. This is fixed in the V0.1.4, appreciate you reporting this as well and testing the mod!

**Comment by ChefMooon** [comment]
Commit 547d52db57b6e0c71a2fc706a93a933f17ca1a41 fixes garlic and recipes related. Fix included in V0.1.4. Appreciate the bug report!

**Comment by reefridgeerator** [comment]
GARLIC IS BACK WOOO
