### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [ChefMooon/ubes-delight#7]
https://pastebin.com/Wk3HyFPT

**Comment by Sunconure11** [comment]
@ChefMooon A hotfix is likely needed.

**Comment by ChefMooon** [comment]
oh my, thank you! Composting value too high for quilt. Hotfix coming shortly.

**Comment by ChefMooon** [comment]
9f089ef3130d71216b65cd10797d7de6c1d4889d 1.20.1
2255c8da4333fd757fa171d3a97a808f1f26eb05 1.19.2

These patches solve the out of bounds error caused on startup for the quilt versions. Hotfixes deployed to V0.1.4a
